name: Update webpage

on:
  schedule:
    - cron: "0 14,21 * * *"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Prepare credentials
        shell: bash
        env:
          GSHEET_CREDS: ${{ secrets.GSHEET_CREDS }}
        run: echo "${GSHEET_CREDS}" > /tmp/gsheet_creds.json

      - name: Generate new webpage
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
        run: python update.py 2>/dev/null

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add index.html *.svg
          git commit -m "Webpage update" || echo "No changes to commit"
          git push
